export const BASELAYOUT_UP_COLLAPSED = 'BASELAYOUT_UP_COLLAPSED'
export const BASELAYOUT_UP_SELLECTEDKEYS = 'BASELAYOUT_UP_SELLECTEDKEYS'
export const BASELAYOUT_UP_OPENKEYS = 'BASELAYOUT_UP_OPENKEYS'
